batch_size:
    - 8
    - 16
    - 32
    - 64
n_chs:
    - 1
n_segments:
    - 1
t_sec:
    - 1
    - 2
    - 4
    - 8
fs:
    - 512
pha_n_bands:
    - 10
amp_n_bands:
    - 10
n_perm:
    -
chunk_size:
    - 1
    - 2
    - 4
    - 8
fp16:
    - true
no_grad:
    - true
in_place:
    - true
trainable:
    - false
device:
    - cuda
use_threads:
    - false
n_calc:
    - 1
    - 2
    - 4
    - 8
package:
    - tensorpac
    - mngs
IS_DEBUG: false
ID: 2024Y-04M-23D-16h26m42s_HKO8
START_TIME: 2024-04-23 16:26:42.325732
SDIR: /home/ywatanabe/proj/torchPAC/scripts/main/RUNNING/2024Y-04M-23D-16h26m42s_HKO8/
END_TIME: 2024-04-23 16:26:44.794842
SPENT_TIME: 00:00:02
