batch_size:
    - 8
    - 16
    - 32
    - 64
n_chs:
    - 1
n_segments:
    - 1
t_sec:
    - 1
    - 2
    - 4
    - 8
fs:
    - 512
pha_n_bands:
    - 10
amp_n_bands:
    - 10
n_perm:
    -
chunk_size:
    - 1
    - 2
    - 4
    - 8
fp16:
    - true
no_grad:
    - true
in_place:
    - true
trainable:
    - false
device:
    - cuda
use_threads:
    - false
n_calc:
    - 1
    - 2
    - 4
    - 8
package:
    - tensorpac
    - mngs
IS_DEBUG: false
ID: 2024Y-04M-23D-18h51m59s_smnC
START_TIME: 2024-04-23 18:51:59.412831
SDIR: 
    /home/ywatanabe/proj/torchPAC/scripts/generate_param_spaces/RUNNING/2024Y-04M-23D-18h51m59s_smnC/
END_TIME: 2024-04-23 18:52:00.507071
SPENT_TIME: 00:00:01
