batch_size:
    - 8
    - 16
    - 32
    - 64
n_chs:
    - 8
    - 16
    - 32
    - 64
seq_len:
    - 256
    - 512
    - 1024
    - 2048
    - 4096
fs:
    - 128
    - 256
    - 512
n_segments:
    - 1
    - 2
    - 4
    - 8
    - 16
n_bands_pha:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
n_bands_amp:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
precision:
    - fp16
    - fp32
device:
    - cpu
    - cuda
package:
    - tensorpac
    - mngs
