batch_size:
    - 1
n_chs:
    - 1
n_segments:
    - 1
t_sec:
    - 1
fs:
    - 512
pha_n_bands:
    - 10
amp_n_bands:
    - 10
n_perm:
    -
chunk_size:
    - 1
fp16:
    - true
no_grad:
    - true
in_place:
    - true
trainable:
    - false
device:
    - cuda
use_threads:
    - false
package:
    - tensorpac
    - mngs
