# Time-stamp: "2024-11-05 20:08:17 (ywatanabe)"
# File: ./torchPAC/config/PATH.yaml

PATH:
  PROCESSOR_USAGE:
    "/tmp/processor_usages.csv"
  RESULTS:
    STATS:
      f"./data/2024Y-11M-05D-12h10m16s_DkUe/condition_{id}/stats.csv"
    PROCESSOR_USAGE:
      f"./data/2024Y-11M-05D-12h10m16s_DkUe/processor_usage.csv"    
    # f"./scripts/main/FINISHED_SUCCESS/2024Y-11M-05D-09h17m20s_LkCN/condition_{id}/stats.csv"
    # f"./scripts/main/FINISHED_SUCCESS/2024Y-11M-05D-05h51m11s_NTtK/condition_{id}/stats.csv"
  # PROC_USAGES:
  #   "./data/processor_usages-20241105_120511-20241105_121317.csv"

    
