batch_size:
    - 8
    - 16
    - 32
    - 64
n_chs:
    - 8
    - 16
    - 32
    - 64
n_segments:
    - 1
    - 2
    - 4
    - 8
    - 16
t_sec:
    - 1
    - 2
    - 4
    - 8
fs:
    - 128
    - 256
    - 512
pha_n_bands:
    - 10
    - 30
    - 50
    - 70
    - 100
amp_n_bands:
    - 10
    - 30
    - 50
    - 70
    - 100
n_perm:
    -
chunk_size:
    - 1
    - 2
    - 4
    - 8
fp16:
    - true
    - false
in_place:
    - false
    - true
trainable:
    - false
    - true
device:
    - cpu
    - cuda
use_threads:
    - false
    - true
package:
    - tensorpac
    - mngs
IS_DEBUG: false
ID: 2024Y-04M-23D-11h26m06s_O5fF
START_TIME: 2024-04-23 11:26:06.169042
SDIR: 
    /home/ywatanabe/proj/entrance/torchPAC/scripts/generate_param_spaces/RUNNING/2024Y-04M-23D-11h26m06s_O5fF/
END_TIME: 2024-04-23 11:26:07.264374
SPENT_TIME: 00:00:01
