batch_size:
    - 8
    - 16
    - 32
    - 64
n_chs:
    - 8
    - 16
    - 32
    - 64
n_segments:
    - 1
    - 2
    - 4
    - 8
    - 16
seq_len:
    - 256
    - 512
    - 1024
    - 2048
    - 4096
fs:
    - 128
    - 256
    - 512
pha_n_bands:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
amp_n_bands:
    - 1
    - 2
    - 4
    - 8
    - 16
    - 32
    - 64
n_perm:
    -
chunk_size:
    - 1
    - 2
    - 4
    - 8
fp16:
    - true
    - false
in_place:
    - false
    - true
trainable:
    - false
    - true
device:
    - cpu
    - cuda
use_threads:
    - false
    - true
package:
    - tensorpac
    - mngs
IS_DEBUG: false
ID: 2024Y-04M-23D-10h35m54s_t9uq
START_TIME: 2024-04-23 10:35:54.293716
SDIR: 
    /home/ywatanabe/proj/entrance/torchPAC/scripts/generate_param_spaces/RUNNING/2024Y-04M-23D-10h35m54s_t9uq/
END_TIME: 2024-04-23 10:35:55.387579
SPENT_TIME: 00:00:01
