batch_size:
    - 8
    - 16
    - 32
    - 64
n_chs:
    - 1
n_segments:
    - 1
t_sec:
    - 1
fs:
    - 512
pha_n_bands:
    - 10
amp_n_bands:
    - 10
n_perm:
    -
chunk_size:
    - 1
fp16:
    - true
no_grad:
    - true
in_place:
    - true
trainable:
    - false
device:
    - cuda
use_threads:
    - false
package:
    - tensorpac
    - mngs
IS_DEBUG: false
ID: 2024Y-04M-23D-15h54m01s_tSgn
START_TIME: 2024-04-23 15:54:01.041334
SDIR: 
    /home/ywatanabe/proj/torchPAC/scripts/summarize/RUNNING/2024Y-04M-23D-15h54m01s_tSgn/
END_TIME: 2024-04-23 15:54:03.395567
SPENT_TIME: 00:00:02
