IS_DEBUG: false
batch_size:
    - 8
n_chs:
    - 8
n_segments:
    - 1
t_sec:
    - 1
fs:
    - 512
pha_n_bands:
    - 10
amp_n_bands:
    - 10
n_perm:
    - 2
    - 4
chunk_size:
    - 1
fp16:
    - true
no_grad:
    - true
in_place:
    - false
trainable:
    - false
device:
    - cuda
use_threads:
    - true
n_calc:
    - 8
package:
    - tensorpac
    - mngs
ID: 2024Y-10M-10D-20h09m56s_D2Yl
START_TIME: 2024-10-10 20:09:56.912294
SDIR: /home/ywatanabe/proj/torchPAC/scripts/main/RUNNING/2024Y-10M-10D-20h09m56s_D2Yl/
REL_SDIR: ./main/
END_TIME: 2024-10-10 20:09:59.921354
SPENT_TIME: 00:00:03
